"""Lexilla's lexer-catalogue names, for create_lexer().

Generated by tools/generate_language_enums.py -- do not hand-edit. Each
member's value is the exact string create_lexer() expects.
"""

import enum


class Language(enum.StrEnum):
    """A lexer name from Lexilla's catalogue, accepted by create_lexer()."""

    COBOL = "COBOL"
    """Lexilla's "COBOL" lexer name, for create_lexer()."""

    DMAP = "DMAP"
    """Lexilla's "DMAP" lexer name, for create_lexer()."""

    DMIS = "DMIS"
    """Lexilla's "DMIS" lexer name, for create_lexer()."""

    PLM = "PL/M"
    """Lexilla's "PL/M" lexer name, for create_lexer()."""

    SML = "SML"
    """Lexilla's "SML" lexer name, for create_lexer()."""

    TACL = "TACL"
    """Lexilla's "TACL" lexer name, for create_lexer()."""

    TAL = "TAL"
    """Lexilla's "TAL" lexer name, for create_lexer()."""

    A68K = "a68k"
    """Lexilla's "a68k" lexer name, for create_lexer()."""

    ABAQUS = "abaqus"
    """Lexilla's "abaqus" lexer name, for create_lexer()."""

    ABL = "abl"
    """Lexilla's "abl" lexer name, for create_lexer()."""

    ADA = "ada"
    """Lexilla's "ada" lexer name, for create_lexer()."""

    APDL = "apdl"
    """Lexilla's "apdl" lexer name, for create_lexer()."""

    AS = "as"
    """Lexilla's "as" lexer name, for create_lexer()."""

    ASCIIDOC = "asciidoc"
    """Lexilla's "asciidoc" lexer name, for create_lexer()."""

    ASM = "asm"
    """Lexilla's "asm" lexer name, for create_lexer()."""

    ASN1 = "asn1"
    """Lexilla's "asn1" lexer name, for create_lexer()."""

    ASY = "asy"
    """Lexilla's "asy" lexer name, for create_lexer()."""

    AU3 = "au3"
    """Lexilla's "au3" lexer name, for create_lexer()."""

    AVE = "ave"
    """Lexilla's "ave" lexer name, for create_lexer()."""

    AVS = "avs"
    """Lexilla's "avs" lexer name, for create_lexer()."""

    BAAN = "baan"
    """Lexilla's "baan" lexer name, for create_lexer()."""

    BASH = "bash"
    """Lexilla's "bash" lexer name, for create_lexer()."""

    BATCH = "batch"
    """Lexilla's "batch" lexer name, for create_lexer()."""

    BIB = "bib"
    """Lexilla's "bib" lexer name, for create_lexer()."""

    BLITZBASIC = "blitzbasic"
    """Lexilla's "blitzbasic" lexer name, for create_lexer()."""

    BULLANT = "bullant"
    """Lexilla's "bullant" lexer name, for create_lexer()."""

    CAML = "caml"
    """Lexilla's "caml" lexer name, for create_lexer()."""

    CIL = "cil"
    """Lexilla's "cil" lexer name, for create_lexer()."""

    CLARION = "clarion"
    """Lexilla's "clarion" lexer name, for create_lexer()."""

    CLARIONNOCASE = "clarionnocase"
    """Lexilla's "clarionnocase" lexer name, for create_lexer()."""

    CMAKE = "cmake"
    """Lexilla's "cmake" lexer name, for create_lexer()."""

    COFFEESCRIPT = "coffeescript"
    """Lexilla's "coffeescript" lexer name, for create_lexer()."""

    CONF = "conf"
    """Lexilla's "conf" lexer name, for create_lexer()."""

    CPP = "cpp"
    """Lexilla's "cpp" lexer name, for create_lexer()."""

    CPPNOCASE = "cppnocase"
    """Lexilla's "cppnocase" lexer name, for create_lexer()."""

    CSOUND = "csound"
    """Lexilla's "csound" lexer name, for create_lexer()."""

    CSS = "css"
    """Lexilla's "css" lexer name, for create_lexer()."""

    D = "d"
    """Lexilla's "d" lexer name, for create_lexer()."""

    DART = "dart"
    """Lexilla's "dart" lexer name, for create_lexer()."""

    DATAFLEX = "dataflex"
    """Lexilla's "dataflex" lexer name, for create_lexer()."""

    DIFF = "diff"
    """Lexilla's "diff" lexer name, for create_lexer()."""

    ECL = "ecl"
    """Lexilla's "ecl" lexer name, for create_lexer()."""

    EDIFACT = "edifact"
    """Lexilla's "edifact" lexer name, for create_lexer()."""

    EIFFEL = "eiffel"
    """Lexilla's "eiffel" lexer name, for create_lexer()."""

    EIFFELKW = "eiffelkw"
    """Lexilla's "eiffelkw" lexer name, for create_lexer()."""

    ERLANG = "erlang"
    """Lexilla's "erlang" lexer name, for create_lexer()."""

    ERRORLIST = "errorlist"
    """Lexilla's "errorlist" lexer name, for create_lexer()."""

    ESCRIPT = "escript"
    """Lexilla's "escript" lexer name, for create_lexer()."""

    ESCSEQ = "escseq"
    """Lexilla's "escseq" lexer name, for create_lexer()."""

    F77 = "f77"
    """Lexilla's "f77" lexer name, for create_lexer()."""

    FCST = "fcST"
    """Lexilla's "fcST" lexer name, for create_lexer()."""

    FLAGSHIP = "flagship"
    """Lexilla's "flagship" lexer name, for create_lexer()."""

    FORTH = "forth"
    """Lexilla's "forth" lexer name, for create_lexer()."""

    FORTRAN = "fortran"
    """Lexilla's "fortran" lexer name, for create_lexer()."""

    FREEBASIC = "freebasic"
    """Lexilla's "freebasic" lexer name, for create_lexer()."""

    FSHARP = "fsharp"
    """Lexilla's "fsharp" lexer name, for create_lexer()."""

    GAP = "gap"
    """Lexilla's "gap" lexer name, for create_lexer()."""

    GDSCRIPT = "gdscript"
    """Lexilla's "gdscript" lexer name, for create_lexer()."""

    GUI4CLI = "gui4cli"
    """Lexilla's "gui4cli" lexer name, for create_lexer()."""

    HASKELL = "haskell"
    """Lexilla's "haskell" lexer name, for create_lexer()."""

    HOLLYWOOD = "hollywood"
    """Lexilla's "hollywood" lexer name, for create_lexer()."""

    HYPERTEXT = "hypertext"
    """Lexilla's "hypertext" lexer name, for create_lexer()."""

    IHEX = "ihex"
    """Lexilla's "ihex" lexer name, for create_lexer()."""

    INDENT = "indent"
    """Lexilla's "indent" lexer name, for create_lexer()."""

    INNO = "inno"
    """Lexilla's "inno" lexer name, for create_lexer()."""

    JSON = "json"
    """Lexilla's "json" lexer name, for create_lexer()."""

    JULIA = "julia"
    """Lexilla's "julia" lexer name, for create_lexer()."""

    KIX = "kix"
    """Lexilla's "kix" lexer name, for create_lexer()."""

    KVIRC = "kvirc"
    """Lexilla's "kvirc" lexer name, for create_lexer()."""

    LATEX = "latex"
    """Lexilla's "latex" lexer name, for create_lexer()."""

    LISP = "lisp"
    """Lexilla's "lisp" lexer name, for create_lexer()."""

    LITERATEHASKELL = "literatehaskell"
    """Lexilla's "literatehaskell" lexer name, for create_lexer()."""

    LOT = "lot"
    """Lexilla's "lot" lexer name, for create_lexer()."""

    LOUT = "lout"
    """Lexilla's "lout" lexer name, for create_lexer()."""

    LUA = "lua"
    """Lexilla's "lua" lexer name, for create_lexer()."""

    MAGIKSF = "magiksf"
    """Lexilla's "magiksf" lexer name, for create_lexer()."""

    MAKEFILE = "makefile"
    """Lexilla's "makefile" lexer name, for create_lexer()."""

    MARKDOWN = "markdown"
    """Lexilla's "markdown" lexer name, for create_lexer()."""

    MATLAB = "matlab"
    """Lexilla's "matlab" lexer name, for create_lexer()."""

    MAXIMA = "maxima"
    """Lexilla's "maxima" lexer name, for create_lexer()."""

    METAPOST = "metapost"
    """Lexilla's "metapost" lexer name, for create_lexer()."""

    MMIXAL = "mmixal"
    """Lexilla's "mmixal" lexer name, for create_lexer()."""

    MODULA = "modula"
    """Lexilla's "modula" lexer name, for create_lexer()."""

    MSSQL = "mssql"
    """Lexilla's "mssql" lexer name, for create_lexer()."""

    MYSQL = "mysql"
    """Lexilla's "mysql" lexer name, for create_lexer()."""

    NIM = "nim"
    """Lexilla's "nim" lexer name, for create_lexer()."""

    NIMROD = "nimrod"
    """Lexilla's "nimrod" lexer name, for create_lexer()."""

    NIX = "nix"
    """Lexilla's "nix" lexer name, for create_lexer()."""

    NNCRONTAB = "nncrontab"
    """Lexilla's "nncrontab" lexer name, for create_lexer()."""

    NSIS = "nsis"
    """Lexilla's "nsis" lexer name, for create_lexer()."""

    NULL = "null"
    """Lexilla's "null" lexer name, for create_lexer()."""

    OCTAVE = "octave"
    """Lexilla's "octave" lexer name, for create_lexer()."""

    OPAL = "opal"
    """Lexilla's "opal" lexer name, for create_lexer()."""

    OSCRIPT = "oscript"
    """Lexilla's "oscript" lexer name, for create_lexer()."""

    PASCAL = "pascal"
    """Lexilla's "pascal" lexer name, for create_lexer()."""

    PERL = "perl"
    """Lexilla's "perl" lexer name, for create_lexer()."""

    PHPSCRIPT = "phpscript"
    """Lexilla's "phpscript" lexer name, for create_lexer()."""

    PO = "po"
    """Lexilla's "po" lexer name, for create_lexer()."""

    POV = "pov"
    """Lexilla's "pov" lexer name, for create_lexer()."""

    POWERBASIC = "powerbasic"
    """Lexilla's "powerbasic" lexer name, for create_lexer()."""

    POWERPRO = "powerpro"
    """Lexilla's "powerpro" lexer name, for create_lexer()."""

    POWERSHELL = "powershell"
    """Lexilla's "powershell" lexer name, for create_lexer()."""

    PROPS = "props"
    """Lexilla's "props" lexer name, for create_lexer()."""

    PS = "ps"
    """Lexilla's "ps" lexer name, for create_lexer()."""

    PUREBASIC = "purebasic"
    """Lexilla's "purebasic" lexer name, for create_lexer()."""

    PYTHON = "python"
    """Lexilla's "python" lexer name, for create_lexer()."""

    R = "r"
    """Lexilla's "r" lexer name, for create_lexer()."""

    RAKU = "raku"
    """Lexilla's "raku" lexer name, for create_lexer()."""

    REBOL = "rebol"
    """Lexilla's "rebol" lexer name, for create_lexer()."""

    REGISTRY = "registry"
    """Lexilla's "registry" lexer name, for create_lexer()."""

    RUBY = "ruby"
    """Lexilla's "ruby" lexer name, for create_lexer()."""

    RUST = "rust"
    """Lexilla's "rust" lexer name, for create_lexer()."""

    SAS = "sas"
    """Lexilla's "sas" lexer name, for create_lexer()."""

    SCRIPTOL = "scriptol"
    """Lexilla's "scriptol" lexer name, for create_lexer()."""

    SINEX = "sinex"
    """Lexilla's "sinex" lexer name, for create_lexer()."""

    SMALLTALK = "smalltalk"
    """Lexilla's "smalltalk" lexer name, for create_lexer()."""

    SORCINS = "sorcins"
    """Lexilla's "sorcins" lexer name, for create_lexer()."""

    SPECMAN = "specman"
    """Lexilla's "specman" lexer name, for create_lexer()."""

    SPICE = "spice"
    """Lexilla's "spice" lexer name, for create_lexer()."""

    SQL = "sql"
    """Lexilla's "sql" lexer name, for create_lexer()."""

    SREC = "srec"
    """Lexilla's "srec" lexer name, for create_lexer()."""

    STATA = "stata"
    """Lexilla's "stata" lexer name, for create_lexer()."""

    TADS3 = "tads3"
    """Lexilla's "tads3" lexer name, for create_lexer()."""

    TCL = "tcl"
    """Lexilla's "tcl" lexer name, for create_lexer()."""

    TCMD = "tcmd"
    """Lexilla's "tcmd" lexer name, for create_lexer()."""

    TEHEX = "tehex"
    """Lexilla's "tehex" lexer name, for create_lexer()."""

    TEX = "tex"
    """Lexilla's "tex" lexer name, for create_lexer()."""

    TOML = "toml"
    """Lexilla's "toml" lexer name, for create_lexer()."""

    TROFF = "troff"
    """Lexilla's "troff" lexer name, for create_lexer()."""

    TXT2TAGS = "txt2tags"
    """Lexilla's "txt2tags" lexer name, for create_lexer()."""

    VB = "vb"
    """Lexilla's "vb" lexer name, for create_lexer()."""

    VBSCRIPT = "vbscript"
    """Lexilla's "vbscript" lexer name, for create_lexer()."""

    VERILOG = "verilog"
    """Lexilla's "verilog" lexer name, for create_lexer()."""

    VHDL = "vhdl"
    """Lexilla's "vhdl" lexer name, for create_lexer()."""

    VISUALPROLOG = "visualprolog"
    """Lexilla's "visualprolog" lexer name, for create_lexer()."""

    X12 = "x12"
    """Lexilla's "x12" lexer name, for create_lexer()."""

    XML = "xml"
    """Lexilla's "xml" lexer name, for create_lexer()."""

    YAML = "yaml"
    """Lexilla's "yaml" lexer name, for create_lexer()."""

    ZIG = "zig"
    """Lexilla's "zig" lexer name, for create_lexer()."""
