#include <cstdint>
#include <memory>

#include <nanobind/nanobind.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/unique_ptr.h>

#include "ILexer.h"
#include "Lexilla.h"

namespace nb = nanobind;
using Scintilla::ILexer5;

namespace {

// Mirrors Scintilla.h's SC_TYPE_* values, returned by ILexer4::PropertyType.
enum class PropertyType {
    Boolean = 0,
    Integer = 1,
    String = 2,
};

// ++Autogenerated (enum) -- run tools/generate_language_enums.py to regenerate
// Mirrors SciLexer.h's SCLEX_* values, returned by ILexer4::GetIdentifier.
enum class LanguageIdentifier {
    CONTAINER = 0,
    NullValue = 1,
    PYTHON = 2,
    CPP = 3,
    HTML = 4,
    XML = 5,
    PERL = 6,
    SQL = 7,
    VB = 8,
    PROPERTIES = 9,
    ERRORLIST = 10,
    MAKEFILE = 11,
    BATCH = 12,
    XCODE = 13,
    LATEX = 14,
    LUA = 15,
    DIFF = 16,
    CONF = 17,
    PASCAL = 18,
    AVE = 19,
    ADA = 20,
    LISP = 21,
    RUBY = 22,
    EIFFEL = 23,
    EIFFELKW = 24,
    TCL = 25,
    NNCRONTAB = 26,
    BULLANT = 27,
    VBSCRIPT = 28,
    BAAN = 31,
    MATLAB = 32,
    SCRIPTOL = 33,
    ASM = 34,
    CPPNOCASE = 35,
    FORTRAN = 36,
    F77 = 37,
    CSS = 38,
    POV = 39,
    LOUT = 40,
    ESCRIPT = 41,
    PS = 42,
    NSIS = 43,
    MMIXAL = 44,
    CLW = 45,
    CLWNOCASE = 46,
    LOT = 47,
    YAML = 48,
    TEX = 49,
    METAPOST = 50,
    POWERBASIC = 51,
    FORTH = 52,
    ERLANG = 53,
    OCTAVE = 54,
    MSSQL = 55,
    VERILOG = 56,
    KIX = 57,
    GUI4CLI = 58,
    SPECMAN = 59,
    AU3 = 60,
    APDL = 61,
    BASH = 62,
    ASN1 = 63,
    VHDL = 64,
    CAML = 65,
    BLITZBASIC = 66,
    PUREBASIC = 67,
    HASKELL = 68,
    PHPSCRIPT = 69,
    TADS3 = 70,
    REBOL = 71,
    SMALLTALK = 72,
    FLAGSHIP = 73,
    CSOUND = 74,
    FREEBASIC = 75,
    INNOSETUP = 76,
    OPAL = 77,
    SPICE = 78,
    D = 79,
    CMAKE = 80,
    GAP = 81,
    PLM = 82,
    PROGRESS = 83,
    ABAQUS = 84,
    ASYMPTOTE = 85,
    R = 86,
    MAGIK = 87,
    POWERSHELL = 88,
    MYSQL = 89,
    PO = 90,
    TAL = 91,
    COBOL = 92,
    TACL = 93,
    SORCUS = 94,
    POWERPRO = 95,
    NIMROD = 96,
    SML = 97,
    MARKDOWN = 98,
    TXT2TAGS = 99,
    A68K = 100,
    MODULA = 101,
    COFFEESCRIPT = 102,
    TCMD = 103,
    AVS = 104,
    ECL = 105,
    OSCRIPT = 106,
    VISUALPROLOG = 107,
    LITERATEHASKELL = 108,
    STTXT = 109,
    KVIRC = 110,
    RUST = 111,
    DMAP = 112,
    AS = 113,
    DMIS = 114,
    REGISTRY = 115,
    BIBTEX = 116,
    SREC = 117,
    IHEX = 118,
    TEHEX = 119,
    JSON = 120,
    EDIFACT = 121,
    INDENT = 122,
    MAXIMA = 123,
    STATA = 124,
    SAS = 125,
    NIM = 126,
    CIL = 127,
    X12 = 128,
    DATAFLEX = 129,
    HOLLYWOOD = 130,
    RAKU = 131,
    FSHARP = 132,
    JULIA = 133,
    ASCIIDOC = 134,
    GDSCRIPT = 135,
    TOML = 136,
    TROFF = 137,
    DART = 138,
    ZIG = 139,
    NIX = 140,
    SINEX = 141,
    ESCSEQ = 142,
    AUTOMATIC = 1000,
};
// --Autogenerated (enum)

// Wraps a single ILexer5* returned by CreateLexer(). Owns it (and calls
// Release() on destruction) until detach() hands ownership to a Scintilla
// editor via SCI_SETILEXER -- see docs/specs/mission.md's "Cross-binding
// integration" decision.
class Lexer {
public:
    explicit Lexer(ILexer5 *lexer) noexcept : lexer_(lexer) {}
    ~Lexer() { ReleaseIfOwned(); }

    Lexer(const Lexer &) = delete;
    Lexer &operator=(const Lexer &) = delete;

    std::uintptr_t Pointer() const { return reinterpret_cast<std::uintptr_t>(Require()); }

    // Hands ownership to the caller (typically a Scintilla editor via
    // SCI_SETILEXER, which will call Release() itself later). After this,
    // the wrapper no longer touches the lexer.
    std::uintptr_t Detach() {
        const std::uintptr_t ptr = reinterpret_cast<std::uintptr_t>(Require());
        owned_ = false;
        lexer_ = nullptr;
        return ptr;
    }

    // Releases the lexer now instead of waiting for garbage collection.
    // No-op if already detached or released.
    void ReleaseNow() { ReleaseIfOwned(); }

    const char *Name() { return Require()->GetName(); }
    LanguageIdentifier Identifier() { return static_cast<LanguageIdentifier>(Require()->GetIdentifier()); }

    const char *PropertyNames() { return Require()->PropertyNames(); }
    PropertyType GetPropertyType(const char *name) { return static_cast<PropertyType>(Require()->PropertyType(name)); }
    const char *DescribeProperty(const char *name) { return Require()->DescribeProperty(name); }
    Sci_Position PropertySet(const char *key, const char *value) { return Require()->PropertySet(key, value); }
    const char *PropertyGet(const char *key) { return Require()->PropertyGet(key); }

    const char *DescribeWordListSets() { return Require()->DescribeWordListSets(); }
    Sci_Position WordListSet(int n, const char *wordList) { return Require()->WordListSet(n, wordList); }

private:
    ILexer5 *Require() const {
        if (!lexer_) {
            throw std::runtime_error("Lexer has been detached or released; this instance no longer owns an ILexer5");
        }
        return lexer_;
    }

    void ReleaseIfOwned() {
        if (owned_ && lexer_) {
            lexer_->Release();
        }
        lexer_ = nullptr;
    }

    ILexer5 *lexer_;
    bool owned_ = true;
};

std::unique_ptr<Lexer> CreateLexerWrapper(const char *name) {
    ILexer5 *lexer = ::CreateLexer(name);
    if (!lexer) {
        return nullptr;
    }
    return std::make_unique<Lexer>(lexer);
}

std::string GetLexerNameWrapper(unsigned int index) {
    char buffer[256];
    ::GetLexerName(index, buffer, sizeof(buffer));
    return std::string(buffer);
}

} // namespace

NB_MODULE(_lexilla, m) {
    nb::enum_<PropertyType>(m, "PropertyType", nb::is_arithmetic(),
        "Value type of a lexer property (see Lexer.property_type), mirroring Scintilla.h's SC_TYPE_*.")
        .value("BOOLEAN", PropertyType::Boolean, "A property whose value is interpreted as 0/1.")
        .value("INTEGER", PropertyType::Integer, "A property whose value is interpreted as an integer.")
        .value("STRING", PropertyType::String, "A property whose value is interpreted as a string.");

    // ++Autogenerated (binding) -- run tools/generate_language_enums.py to regenerate
    nb::enum_<LanguageIdentifier>(m, "LanguageIdentifier", nb::is_arithmetic(),
        "Numeric language identifier of a lexer (see Lexer.identifier), mirroring SciLexer.h's SCLEX_*.")
        .value("CONTAINER", LanguageIdentifier::CONTAINER, "Reserved; SCLEX_CONTAINER is defined but has no associated lexer.")
        .value("NULL", LanguageIdentifier::NullValue, "Reserved; SCLEX_NULL is defined but has no associated lexer.")
        .value("PYTHON", LanguageIdentifier::PYTHON, "Identifier for the \"python\" lexer.")
        .value("CPP", LanguageIdentifier::CPP, "Identifier for the \"cpp\" lexer.")
        .value("HTML", LanguageIdentifier::HTML, "Identifier for the \"hypertext\" lexer.")
        .value("XML", LanguageIdentifier::XML, "Identifier for the \"xml\" lexer.")
        .value("PERL", LanguageIdentifier::PERL, "Identifier for the \"perl\" lexer.")
        .value("SQL", LanguageIdentifier::SQL, "Identifier for the \"sql\" lexer.")
        .value("VB", LanguageIdentifier::VB, "Identifier for the \"vb\" lexer.")
        .value("PROPERTIES", LanguageIdentifier::PROPERTIES, "Identifier for the \"props\" lexer.")
        .value("ERRORLIST", LanguageIdentifier::ERRORLIST, "Identifier for the \"errorlist\" lexer.")
        .value("MAKEFILE", LanguageIdentifier::MAKEFILE, "Identifier for the \"makefile\" lexer.")
        .value("BATCH", LanguageIdentifier::BATCH, "Identifier for the \"batch\" lexer.")
        .value("XCODE", LanguageIdentifier::XCODE, "Reserved; SCLEX_XCODE is defined but has no associated lexer.")
        .value("LATEX", LanguageIdentifier::LATEX, "Identifier for the \"latex\" lexer.")
        .value("LUA", LanguageIdentifier::LUA, "Identifier for the \"lua\" lexer.")
        .value("DIFF", LanguageIdentifier::DIFF, "Identifier for the \"diff\" lexer.")
        .value("CONF", LanguageIdentifier::CONF, "Identifier for the \"conf\" lexer.")
        .value("PASCAL", LanguageIdentifier::PASCAL, "Identifier for the \"pascal\" lexer.")
        .value("AVE", LanguageIdentifier::AVE, "Identifier for the \"ave\" lexer.")
        .value("ADA", LanguageIdentifier::ADA, "Identifier for the \"ada\" lexer.")
        .value("LISP", LanguageIdentifier::LISP, "Identifier for the \"lisp\" lexer.")
        .value("RUBY", LanguageIdentifier::RUBY, "Identifier for the \"ruby\" lexer.")
        .value("EIFFEL", LanguageIdentifier::EIFFEL, "Identifier for the \"eiffel\" lexer.")
        .value("EIFFELKW", LanguageIdentifier::EIFFELKW, "Identifier for the \"eiffelkw\" lexer.")
        .value("TCL", LanguageIdentifier::TCL, "Identifier for the \"tcl\" lexer.")
        .value("NNCRONTAB", LanguageIdentifier::NNCRONTAB, "Identifier for the \"nncrontab\" lexer.")
        .value("BULLANT", LanguageIdentifier::BULLANT, "Identifier for the \"bullant\" lexer.")
        .value("VBSCRIPT", LanguageIdentifier::VBSCRIPT, "Identifier for the \"vbscript\" lexer.")
        .value("BAAN", LanguageIdentifier::BAAN, "Identifier for the \"baan\" lexer.")
        .value("MATLAB", LanguageIdentifier::MATLAB, "Identifier for the \"matlab\" lexer.")
        .value("SCRIPTOL", LanguageIdentifier::SCRIPTOL, "Identifier for the \"scriptol\" lexer.")
        .value("ASM", LanguageIdentifier::ASM, "Identifier for the \"asm\" lexer.")
        .value("CPPNOCASE", LanguageIdentifier::CPPNOCASE, "Identifier for the \"cppnocase\" lexer.")
        .value("FORTRAN", LanguageIdentifier::FORTRAN, "Identifier for the \"fortran\" lexer.")
        .value("F77", LanguageIdentifier::F77, "Identifier for the \"f77\" lexer.")
        .value("CSS", LanguageIdentifier::CSS, "Identifier for the \"css\" lexer.")
        .value("POV", LanguageIdentifier::POV, "Identifier for the \"pov\" lexer.")
        .value("LOUT", LanguageIdentifier::LOUT, "Identifier for the \"lout\" lexer.")
        .value("ESCRIPT", LanguageIdentifier::ESCRIPT, "Identifier for the \"escript\" lexer.")
        .value("PS", LanguageIdentifier::PS, "Identifier for the \"ps\" lexer.")
        .value("NSIS", LanguageIdentifier::NSIS, "Identifier for the \"nsis\" lexer.")
        .value("MMIXAL", LanguageIdentifier::MMIXAL, "Identifier for the \"mmixal\" lexer.")
        .value("CLW", LanguageIdentifier::CLW, "Identifier for the \"clarion\" lexer.")
        .value("CLWNOCASE", LanguageIdentifier::CLWNOCASE, "Identifier for the \"clarionnocase\" lexer.")
        .value("LOT", LanguageIdentifier::LOT, "Identifier for the \"lot\" lexer.")
        .value("YAML", LanguageIdentifier::YAML, "Identifier for the \"yaml\" lexer.")
        .value("TEX", LanguageIdentifier::TEX, "Identifier for the \"tex\" lexer.")
        .value("METAPOST", LanguageIdentifier::METAPOST, "Identifier for the \"metapost\" lexer.")
        .value("POWERBASIC", LanguageIdentifier::POWERBASIC, "Identifier for the \"powerbasic\" lexer.")
        .value("FORTH", LanguageIdentifier::FORTH, "Identifier for the \"forth\" lexer.")
        .value("ERLANG", LanguageIdentifier::ERLANG, "Identifier for the \"erlang\" lexer.")
        .value("OCTAVE", LanguageIdentifier::OCTAVE, "Identifier for the \"octave\" lexer.")
        .value("MSSQL", LanguageIdentifier::MSSQL, "Identifier for the \"mssql\" lexer.")
        .value("VERILOG", LanguageIdentifier::VERILOG, "Identifier for the \"verilog\" lexer.")
        .value("KIX", LanguageIdentifier::KIX, "Identifier for the \"kix\" lexer.")
        .value("GUI4CLI", LanguageIdentifier::GUI4CLI, "Identifier for the \"gui4cli\" lexer.")
        .value("SPECMAN", LanguageIdentifier::SPECMAN, "Identifier for the \"specman\" lexer.")
        .value("AU3", LanguageIdentifier::AU3, "Identifier for the \"au3\" lexer.")
        .value("APDL", LanguageIdentifier::APDL, "Identifier for the \"apdl\" lexer.")
        .value("BASH", LanguageIdentifier::BASH, "Identifier for the \"bash\" lexer.")
        .value("ASN1", LanguageIdentifier::ASN1, "Identifier for the \"asn1\" lexer.")
        .value("VHDL", LanguageIdentifier::VHDL, "Identifier for the \"vhdl\" lexer.")
        .value("CAML", LanguageIdentifier::CAML, "Identifier for the \"caml\" lexer.")
        .value("BLITZBASIC", LanguageIdentifier::BLITZBASIC, "Identifier for the \"blitzbasic\" lexer.")
        .value("PUREBASIC", LanguageIdentifier::PUREBASIC, "Identifier for the \"purebasic\" lexer.")
        .value("HASKELL", LanguageIdentifier::HASKELL, "Identifier for the \"haskell\" lexer.")
        .value("PHPSCRIPT", LanguageIdentifier::PHPSCRIPT, "Identifier for the \"phpscript\" lexer.")
        .value("TADS3", LanguageIdentifier::TADS3, "Identifier for the \"tads3\" lexer.")
        .value("REBOL", LanguageIdentifier::REBOL, "Identifier for the \"rebol\" lexer.")
        .value("SMALLTALK", LanguageIdentifier::SMALLTALK, "Identifier for the \"smalltalk\" lexer.")
        .value("FLAGSHIP", LanguageIdentifier::FLAGSHIP, "Identifier for the \"flagship\" lexer.")
        .value("CSOUND", LanguageIdentifier::CSOUND, "Identifier for the \"csound\" lexer.")
        .value("FREEBASIC", LanguageIdentifier::FREEBASIC, "Identifier for the \"freebasic\" lexer.")
        .value("INNOSETUP", LanguageIdentifier::INNOSETUP, "Identifier for the \"inno\" lexer.")
        .value("OPAL", LanguageIdentifier::OPAL, "Identifier for the \"opal\" lexer.")
        .value("SPICE", LanguageIdentifier::SPICE, "Identifier for the \"spice\" lexer.")
        .value("D", LanguageIdentifier::D, "Identifier for the \"d\" lexer.")
        .value("CMAKE", LanguageIdentifier::CMAKE, "Identifier for the \"cmake\" lexer.")
        .value("GAP", LanguageIdentifier::GAP, "Identifier for the \"gap\" lexer.")
        .value("PLM", LanguageIdentifier::PLM, "Identifier for the \"PL/M\" lexer.")
        .value("PROGRESS", LanguageIdentifier::PROGRESS, "Identifier for the \"abl\" lexer.")
        .value("ABAQUS", LanguageIdentifier::ABAQUS, "Identifier for the \"abaqus\" lexer.")
        .value("ASYMPTOTE", LanguageIdentifier::ASYMPTOTE, "Identifier for the \"asy\" lexer.")
        .value("R", LanguageIdentifier::R, "Identifier for the \"r\" lexer.")
        .value("MAGIK", LanguageIdentifier::MAGIK, "Identifier for the \"magiksf\" lexer.")
        .value("POWERSHELL", LanguageIdentifier::POWERSHELL, "Identifier for the \"powershell\" lexer.")
        .value("MYSQL", LanguageIdentifier::MYSQL, "Identifier for the \"mysql\" lexer.")
        .value("PO", LanguageIdentifier::PO, "Identifier for the \"po\" lexer.")
        .value("TAL", LanguageIdentifier::TAL, "Identifier for the \"TAL\" lexer.")
        .value("COBOL", LanguageIdentifier::COBOL, "Identifier for the \"COBOL\" lexer.")
        .value("TACL", LanguageIdentifier::TACL, "Identifier for the \"TACL\" lexer.")
        .value("SORCUS", LanguageIdentifier::SORCUS, "Identifier for the \"sorcins\" lexer.")
        .value("POWERPRO", LanguageIdentifier::POWERPRO, "Identifier for the \"powerpro\" lexer.")
        .value("NIMROD", LanguageIdentifier::NIMROD, "Identifier for the \"nimrod\" lexer.")
        .value("SML", LanguageIdentifier::SML, "Identifier for the \"SML\" lexer.")
        .value("MARKDOWN", LanguageIdentifier::MARKDOWN, "Identifier for the \"markdown\" lexer.")
        .value("TXT2TAGS", LanguageIdentifier::TXT2TAGS, "Identifier for the \"txt2tags\" lexer.")
        .value("A68K", LanguageIdentifier::A68K, "Identifier for the \"a68k\" lexer.")
        .value("MODULA", LanguageIdentifier::MODULA, "Identifier for the \"modula\" lexer.")
        .value("COFFEESCRIPT", LanguageIdentifier::COFFEESCRIPT, "Identifier for the \"coffeescript\" lexer.")
        .value("TCMD", LanguageIdentifier::TCMD, "Identifier for the \"tcmd\" lexer.")
        .value("AVS", LanguageIdentifier::AVS, "Identifier for the \"avs\" lexer.")
        .value("ECL", LanguageIdentifier::ECL, "Identifier for the \"ecl\" lexer.")
        .value("OSCRIPT", LanguageIdentifier::OSCRIPT, "Identifier for the \"oscript\" lexer.")
        .value("VISUALPROLOG", LanguageIdentifier::VISUALPROLOG, "Identifier for the \"visualprolog\" lexer.")
        .value("LITERATEHASKELL", LanguageIdentifier::LITERATEHASKELL, "Identifier for the \"literatehaskell\" lexer.")
        .value("STTXT", LanguageIdentifier::STTXT, "Identifier for the \"fcST\" lexer.")
        .value("KVIRC", LanguageIdentifier::KVIRC, "Identifier for the \"kvirc\" lexer.")
        .value("RUST", LanguageIdentifier::RUST, "Identifier for the \"rust\" lexer.")
        .value("DMAP", LanguageIdentifier::DMAP, "Identifier for the \"DMAP\" lexer.")
        .value("AS", LanguageIdentifier::AS, "Identifier for the \"as\" lexer.")
        .value("DMIS", LanguageIdentifier::DMIS, "Identifier for the \"DMIS\" lexer.")
        .value("REGISTRY", LanguageIdentifier::REGISTRY, "Identifier for the \"registry\" lexer.")
        .value("BIBTEX", LanguageIdentifier::BIBTEX, "Identifier for the \"bib\" lexer.")
        .value("SREC", LanguageIdentifier::SREC, "Identifier for the \"srec\" lexer.")
        .value("IHEX", LanguageIdentifier::IHEX, "Identifier for the \"ihex\" lexer.")
        .value("TEHEX", LanguageIdentifier::TEHEX, "Identifier for the \"tehex\" lexer.")
        .value("JSON", LanguageIdentifier::JSON, "Identifier for the \"json\" lexer.")
        .value("EDIFACT", LanguageIdentifier::EDIFACT, "Identifier for the \"edifact\" lexer.")
        .value("INDENT", LanguageIdentifier::INDENT, "Identifier for the \"indent\" lexer.")
        .value("MAXIMA", LanguageIdentifier::MAXIMA, "Identifier for the \"maxima\" lexer.")
        .value("STATA", LanguageIdentifier::STATA, "Identifier for the \"stata\" lexer.")
        .value("SAS", LanguageIdentifier::SAS, "Identifier for the \"sas\" lexer.")
        .value("NIM", LanguageIdentifier::NIM, "Identifier for the \"nim\" lexer.")
        .value("CIL", LanguageIdentifier::CIL, "Identifier for the \"cil\" lexer.")
        .value("X12", LanguageIdentifier::X12, "Identifier for the \"x12\" lexer.")
        .value("DATAFLEX", LanguageIdentifier::DATAFLEX, "Identifier for the \"dataflex\" lexer.")
        .value("HOLLYWOOD", LanguageIdentifier::HOLLYWOOD, "Identifier for the \"hollywood\" lexer.")
        .value("RAKU", LanguageIdentifier::RAKU, "Identifier for the \"raku\" lexer.")
        .value("FSHARP", LanguageIdentifier::FSHARP, "Identifier for the \"fsharp\" lexer.")
        .value("JULIA", LanguageIdentifier::JULIA, "Identifier for the \"julia\" lexer.")
        .value("ASCIIDOC", LanguageIdentifier::ASCIIDOC, "Identifier for the \"asciidoc\" lexer.")
        .value("GDSCRIPT", LanguageIdentifier::GDSCRIPT, "Identifier for the \"gdscript\" lexer.")
        .value("TOML", LanguageIdentifier::TOML, "Identifier for the \"toml\" lexer.")
        .value("TROFF", LanguageIdentifier::TROFF, "Identifier for the \"troff\" lexer.")
        .value("DART", LanguageIdentifier::DART, "Identifier for the \"dart\" lexer.")
        .value("ZIG", LanguageIdentifier::ZIG, "Identifier for the \"zig\" lexer.")
        .value("NIX", LanguageIdentifier::NIX, "Identifier for the \"nix\" lexer.")
        .value("SINEX", LanguageIdentifier::SINEX, "Identifier for the \"sinex\" lexer.")
        .value("ESCSEQ", LanguageIdentifier::ESCSEQ, "Identifier for the \"escseq\" lexer.")
        .value("AUTOMATIC", LanguageIdentifier::AUTOMATIC, "Sentinel requesting automatic lexer selection; not itself a lexer.");
    // --Autogenerated (binding)

    nb::class_<Lexer>(m, "Lexer")
        .def_prop_ro("pointer", &Lexer::Pointer,
            "Raw ILexer5* as a plain int, e.g. for SCI_SETILEXER. Does not transfer ownership.")
        .def("detach", &Lexer::Detach,
            "Hand ownership to the caller (e.g. a Scintilla editor) and stop managing this lexer's lifetime.")
        .def("release", &Lexer::ReleaseNow,
            "Release the lexer now rather than waiting for garbage collection. No-op if detached or already released.")
        .def_prop_ro("name", &Lexer::Name,
            "This lexer's name, as passed to create_lexer().")
        .def_prop_ro("identifier", &Lexer::Identifier,
            "This lexer's language identifier (see the LanguageIdentifier enum).")
        .def("property_names", &Lexer::PropertyNames,
            "Newline-separated list of property keys this lexer recognizes via property_set/property_get.")
        .def("property_type", &Lexer::GetPropertyType, nb::arg("name"),
            "Value type of the named property (see the PropertyType enum).")
        .def("describe_property", &Lexer::DescribeProperty, nb::arg("name"),
            "Human-readable description of what the named property controls.")
        .def("property_set", &Lexer::PropertySet, nb::arg("key"), nb::arg("value"),
            "Set a lexer property; returns a Sci_Position invalidation hint (lexer-specific, often 0).")
        .def("property_get", &Lexer::PropertyGet, nb::arg("key"),
            "Current value of a lexer property previously set via property_set, or its default.")
        .def("describe_word_list_sets", &Lexer::DescribeWordListSets,
            "Newline-separated description of each word-list slot accepted by word_list_set.")
        .def("word_list_set", &Lexer::WordListSet, nb::arg("n"), nb::arg("word_list"),
            "Set word-list slot n (see describe_word_list_sets) to a space-separated list of words.");

    m.def("create_lexer", &CreateLexerWrapper, nb::arg("name"),
        "Create a lexer by name (e.g. \"cpp\"), or None if no lexer has that name.");
    m.def("get_lexer_count", &GetLexerCount,
        "Number of lexers in Lexilla's catalogue, for iterating get_lexer_name(0..count-1).");
    m.def("get_lexer_name", &GetLexerNameWrapper, nb::arg("index"),
        "Name of the lexer at the given catalogue index, suitable for passing to create_lexer().");
}
