#!/usr/bin/env python3
"""Regenerate LanguageIdentifier (C++) and Language (Python) enums.

One-off, manually-run generator -- NOT part of the normal build (see
`make generate-language-enums`). Re-run after re-vendoring
src/lexilla_vendor/ (see docs/auditing.md's re-vendoring checklist).

Sources:
- src/lexilla_vendor/scripts/LexillaData.py (vendored, unmodified) for the
  lexer-name -> SCLEX_* macro-name mapping it already parses out of
  lexers/Lex*.cxx.
- src/lexilla_vendor/include/SciLexer.h, regexed directly for the numeric
  value of each SCLEX_* macro (LexillaData only has the macro name).

Outputs, both spliced into src/lexilla/bindings/_binding.cpp between their
own `// ++Autogenerated` / `// --Autogenerated` marker pair (two pairs,
since the enum class must be visible to Lexer::Identifier() in the
anonymous namespace, while its nb::enum_<> registration needs `m` and can
only happen inside NB_MODULE):
- `enum class LanguageIdentifier { ... };`, next to PropertyType.
- its `nb::enum_<LanguageIdentifier>(...)` registration, next to
  PropertyType's.

Also writes src/lexilla/_languages.py from scratch (a Language(StrEnum)
with one member per lexer-catalogue name).
"""

import pathlib
import re
import sys
from typing import Final

REPO_ROOT: Final = pathlib.Path(__file__).resolve().parent.parent
"""Root of the lexilla-py checkout, two levels up from this script."""

VENDOR_ROOT: Final = REPO_ROOT / "src" / "lexilla_vendor"
"""Root of the vendored Lexilla release tarball."""

SCILEXER_H: Final = VENDOR_ROOT / "include" / "SciLexer.h"
"""Header declaring the SCLEX_* macros this script regexes for numeric values."""

BINDING_CPP: Final = REPO_ROOT / "src" / "lexilla" / "bindings" / "_binding.cpp"
"""nanobind binding source the LanguageIdentifier enum/registration are spliced into."""

LANGUAGES_PY: Final = REPO_ROOT / "src" / "lexilla" / "_languages.py"
"""Generated Language(StrEnum) module, rewritten from scratch on every run."""

NO_LEXER_MACROS: Final = {"CONTAINER", "NULL", "AUTOMATIC", "XCODE"}
"""SCLEX_* macros with no associated LexerModule/lexer name."""

MEMBER_NAME_OVERRIDES: Final = {"PL/M": "PLM"}
"""The only catalogue lexer name that isn't a valid Python identifier once
upper-cased (the others, e.g. "fcST" -> "FCST", already are)."""

CPP_MEMBER_NAME_OVERRIDES: Final = {"NULL": "NullValue"}
"""SCLEX_* macro suffixes that aren't usable as a C++ enumerator name as-is.

NULL collides with the <cstddef> NULL macro (the preprocessor would rewrite
"NULL = 1," before the compiler ever sees an identifier). The Python-facing
name stays "NULL" via the .value() registration string."""

ENUM_START: Final = "// ++Autogenerated (enum) -- run tools/generate_language_enums.py to regenerate"
"""Marks the start of the spliced `enum class LanguageIdentifier` block."""

ENUM_END: Final = "// --Autogenerated (enum)"
"""Marks the end of the spliced `enum class LanguageIdentifier` block."""

BINDING_START: Final = "// ++Autogenerated (binding) -- run tools/generate_language_enums.py to regenerate"
"""Marks the start of the spliced nb::enum_<LanguageIdentifier> registration block."""

BINDING_END: Final = "// --Autogenerated (binding)"
"""Marks the end of the spliced nb::enum_<LanguageIdentifier> registration block."""

ENUM_ANCHOR: Final = "// Wraps a single ILexer5* returned by CreateLexer()."
"""Insertion point used only the first time this script runs against a file with no ENUM_START/ENUM_END pair yet."""

BINDING_ANCHOR: Final = 'nb::class_<Lexer>(m, "Lexer")'
"""Insertion point used only the first time this script runs against a file with no BINDING_START/BINDING_END pair yet."""

LANGUAGES_PY_HEADER: Final = '''"""Lexilla's lexer-catalogue names, for create_lexer().

Generated by tools/generate_language_enums.py -- do not hand-edit. Each
member's value is the exact string create_lexer() expects.
"""

import enum


class Language(enum.StrEnum):
    """A lexer name from Lexilla's catalogue, accepted by create_lexer()."""
'''
"""Static module docstring/imports/class header for the generated _languages.py; per-member lines are appended after it."""


def load_sclex_from_name() -> dict[str, str]:
    """Lexer name -> full SCLEX_* macro name, via vendored LexillaData.py."""
    sys.path.insert(0, str(VENDOR_ROOT / "scripts"))
    import LexillaData  # noqa: PLC0415 (vendored module, path-injected)

    data = LexillaData.LexillaData(VENDOR_ROOT)
    return data.sclexFromName


def load_macro_values() -> dict[str, int]:
    """Full SCLEX_* macro name -> its numeric value, regexed from SciLexer.h."""
    text = SCILEXER_H.read_text(encoding="utf-8")
    return {
        f"SCLEX_{m.group(1)}": int(m.group(2)) for m in re.finditer(r"^#define SCLEX_(\w+) (\d+)", text, re.MULTILINE)
    }


def member_name_for(lexer_name: str) -> str:
    """Language enum member name for a catalogue lexer name (see MEMBER_NAME_OVERRIDES)."""
    return MEMBER_NAME_OVERRIDES.get(lexer_name, lexer_name.upper())


def doc_for(suffix: str, macro: str, name_from_macro: dict[str, str]) -> str:
    """Per-value docstring for a LanguageIdentifier member, given its SCLEX_* suffix/macro."""
    if suffix in NO_LEXER_MACROS:
        if suffix == "AUTOMATIC":
            return "Sentinel requesting automatic lexer selection; not itself a lexer."
        return f"Reserved; {macro} is defined but has no associated lexer."
    lexer_name = name_from_macro[macro]
    return f'Identifier for the \\"{lexer_name}\\" lexer.'


def generate_enum_block(macro_values: dict[str, int]) -> str:
    """C++ source for the `enum class LanguageIdentifier { ... };` definition."""
    lines = [
        ENUM_START,
        "// Mirrors SciLexer.h's SCLEX_* values, returned by ILexer4::GetIdentifier.",
        "enum class LanguageIdentifier {",
    ]
    for macro, value in sorted(macro_values.items(), key=lambda kv: kv[1]):
        suffix = macro.removeprefix("SCLEX_")
        cpp_name = CPP_MEMBER_NAME_OVERRIDES.get(suffix, suffix)
        lines.append(f"    {cpp_name} = {value},")
    lines.append("};")
    lines.append(ENUM_END)
    return "\n".join(lines)


def generate_binding_block(macro_values: dict[str, int], name_from_macro: dict[str, str]) -> str:
    """C++ source for LanguageIdentifier's nb::enum_<> registration, with per-value docs."""
    lines = [
        BINDING_START,
        'nb::enum_<LanguageIdentifier>(m, "LanguageIdentifier", nb::is_arithmetic(),',
        '    "Numeric language identifier of a lexer (see Lexer.identifier), mirroring SciLexer.h\'s SCLEX_*.")',
    ]
    value_lines = []
    for macro, value in sorted(macro_values.items(), key=lambda kv: kv[1]):
        suffix = macro.removeprefix("SCLEX_")
        cpp_name = CPP_MEMBER_NAME_OVERRIDES.get(suffix, suffix)
        doc = doc_for(suffix, macro, name_from_macro)
        value_lines.append(f'    .value("{suffix}", LanguageIdentifier::{cpp_name}, "{doc}")')
    lines.append("\n".join(value_lines) + ";")
    lines.append(BINDING_END)
    return "\n".join(lines)


def indent(block: str, prefix: str) -> str:
    """Prefix every non-empty line of block with prefix, leaving blank lines untouched."""
    return "\n".join(prefix + line if line else line for line in block.split("\n"))


def splice(text: str, start_marker: str, end_marker: str, block: str, anchor: str, prefix: str) -> str:
    """Replace the marker-delimited region in text with block, or insert it next to anchor on a first run."""
    indented = indent(block, prefix)
    pattern = re.compile(r"[ \t]*" + re.escape(start_marker) + r".*?" + re.escape(end_marker), re.DOTALL)
    if pattern.search(text):
        return pattern.sub(indented, text)
    return text.replace(anchor, indented + "\n\n" + prefix + anchor)


def generate_languages_py(lexer_names: list[str]) -> str:
    """Full source for src/lexilla/_languages.py, a Language(StrEnum) with one member per lexer name."""
    members = "".join(
        f'\n    {member_name_for(name)} = "{name}"\n    """Lexilla\'s "{name}" lexer name, for create_lexer()."""\n'
        for name in sorted(lexer_names)
    )
    return LANGUAGES_PY_HEADER + members


def main() -> None:
    """Regenerate LanguageIdentifier in _binding.cpp and rewrite _languages.py."""
    sclex_from_name = load_sclex_from_name()
    macro_values = load_macro_values()

    macros_with_lexer = set(sclex_from_name.values())
    macros_without_lexer = {f"SCLEX_{m}" for m in NO_LEXER_MACROS}
    all_macros = set(macro_values)
    unaccounted = all_macros - macros_with_lexer - macros_without_lexer
    assert not unaccounted, f"SCLEX_* macros with no LexerModule and not in NO_LEXER_MACROS: {unaccounted}"
    missing = (macros_with_lexer | macros_without_lexer) - all_macros
    assert not missing, f"Expected SCLEX_* macros missing from SciLexer.h: {missing}"

    name_from_macro = {macro: name for name, macro in sclex_from_name.items()}

    text = BINDING_CPP.read_text(encoding="utf-8")
    text = splice(text, ENUM_START, ENUM_END, generate_enum_block(macro_values), ENUM_ANCHOR, prefix="")
    text = splice(
        text,
        BINDING_START,
        BINDING_END,
        generate_binding_block(macro_values, name_from_macro),
        BINDING_ANCHOR,
        prefix="    ",
    )
    BINDING_CPP.write_text(text, encoding="utf-8")

    LANGUAGES_PY.write_text(generate_languages_py(list(sclex_from_name.keys())), encoding="utf-8")

    print(f"LanguageIdentifier: {len(macro_values)} values -> {BINDING_CPP}")
    print(f"Language: {len(sclex_from_name)} values -> {LANGUAGES_PY}")


if __name__ == "__main__":
    main()
